### ISSUE TITLE
MLSVM Installation

### ISSUE THREAD

**Issue by kspalm** [esadr/mlsvm#6]
- Clone repository with `git clone --recursive https://github.com/esadr/mlsvm.git`

- Go to the resulting `/mlsvm/petsc/` directory and install PETSc by first configuring it and then running make:
    `./configure PETSC_ARCH=<build path> --with-cc=gcc --with-cxx=g++ --with-clanguage=c++ --with-gnu-compilers=1 --with-mpi-compilers=1 --with-debugging=0 --with-shared-libraries=1 --download-openmpi=1 --download-f2cblaslapack --download-metis=1 --download-parmetis=1 --download-blacs=1 --download-cmake`
    - Creates a new directory with same name as what was used for `<build path>` in `PETSC_ARCH=<build path>`
    - `--download-cmake` only needed if cmake is not installed
    - Then run make:
    `make all test`

- Update environment variables PETSC_DIR and PETSC_ARCH
    - PETSC_DIR needs to point to the PETSc installation just made
        - Example: `PETSC_DIR=/home/username/mlsvm/petsc`
    - PETSC_ARCH should be the same as what was used for `./configure`
        - Example: `PETSC_ARCH=linux-cxx-fast`

- Go to `mlsvm/src/` and run:
    `make`

Notes:
- `./configure` can take a while if downloading several things
- `make all test` will recommend running `make PETSC_DIR=<build path> streams`; this will determine speed up gained by using an increasing number of processors, starting from 1 and going up to the number of processors available. Be careful when running on a system with a lot of them! It's not necessary to finish installation, though it may be useful.
- I have not yet attempted to install pyflann

**Comment by esadr** [comment]
Thanks for adding the steps.
